name: Deploy

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - run: bundle config set deployment 'true'
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - run: bundle exec middleman build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        keep_files: true

    - name: Release
      run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}

    - name: Slack Deploy / Release Alert
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        channel: ${{ secrets.SLACK_RELEASE_CHANNEL_ID }}
        fields: 'repo,commit,message,workflow,job'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
